package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Controller.KoneksiDatabase;
import View.RegistrasiForm;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Nuno
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        nama_login = new javax.swing.JLabel();
        text3_login = new javax.swing.JLabel();
        text2_login = new javax.swing.JLabel();
        pw_login = new javax.swing.JPasswordField();
        pilihanrole_login = new javax.swing.JComboBox<>();
        login = new javax.swing.JButton();
        text1_login = new javax.swing.JLabel();
        lblDaftar = new javax.swing.JLabel();
        namasistem_login = new javax.swing.JLabel();
        logo_login = new javax.swing.JLabel();
        bg_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(12, 51, 56));
        jLabel9.setText("Role");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 51, 56));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        textField2.setForeground(new java.awt.Color(12, 51, 56));
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 380, 30));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 51, 56));
        jLabel7.setText("Username");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.setForeground(new java.awt.Color(12, 51, 56));
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 380, 30));

        nama_login.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        nama_login.setForeground(new java.awt.Color(12, 51, 56));
        nama_login.setText("Nama");
        getContentPane().add(nama_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        text3_login.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        text3_login.setForeground(new java.awt.Color(12, 51, 56));
        text3_login.setText("Kelola dan pantau distribusi pangan daerah secara terintegrasi.");
        getContentPane().add(text3_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        text2_login.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        text2_login.setForeground(new java.awt.Color(12, 51, 56));
        text2_login.setText("Selamat Datang di SI-KETANDA");
        getContentPane().add(text2_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, 30));

        pw_login.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        pw_login.setForeground(new java.awt.Color(12, 51, 56));
        getContentPane().add(pw_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 380, 30));

        pilihanrole_login.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        pilihanrole_login.setForeground(new java.awt.Color(12, 51, 56));
        pilihanrole_login.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pemerintah", "Petani", "Customer", "Distributor" }));
        pilihanrole_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanrole_loginActionPerformed(evt);
            }
        });
        getContentPane().add(pilihanrole_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 380, 30));

        login.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(12, 51, 56));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 80, 30));

        text1_login.setText("Belum punya akun?");
        getContentPane().add(text1_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        lblDaftar.setText("Daftar");
        lblDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDaftarMouseClicked(evt);
            }
        });
        getContentPane().add(lblDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, -1, -1));

        namasistem_login.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        namasistem_login.setForeground(new java.awt.Color(255, 255, 255));
        namasistem_login.setText("Sistem Ketahanan Pangan Daerah");
        getContentPane().add(namasistem_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        logo_login.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nuno\\Downloads\\logo (1).png")); // NOI18N
        getContentPane().add(logo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 50, 60));

        bg_login.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nuno\\Downloads\\Green and Yellow Modern Simple Travel Login Page Wireframe Tablet Prototype (2).jpg")); // NOI18N
        getContentPane().add(bg_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:                                 
    // Ambil input dari form
    String username = textField2.getText().trim();
    String password = new String(pw_login.getPassword());
    String role = pilihanrole_login.getSelectedItem().toString();

    // Validasi input kosong
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan password harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Koneksi ke database
        Connection conn = KoneksiDatabase.getConnection();
        String sql = "SELECT * FROM user WHERE username=? AND password=? AND role=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, username);
        ps.setString(2, password);
        ps.setString(3, role);
        ResultSet rs = ps.executeQuery();

        // Cek hasil login
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Login berhasil sebagai " + role + "!");

            // Arahkan ke dashboard sesuai role
            switch (role) {
                case "Admin":
                    new View.admin.DashboardAdmin().setVisible(true);
                    break;
                case "Pemerintah":
                    new View.admin.DBAdminKelolaWilayah().setVisible(true);
                    break;
                case "Petani":
                    new View.DashboardPetani().setVisible(true);
                    break;
                case "Customer":
                    new View.customer.DBCustomerLihatKomoditas().setVisible(true);
                    break;
                case "Distributor":
                    new View.DashboardDistributor().setVisible(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Role tidak dikenali!", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
            }

            this.dispose(); // tutup login form
        } else {
            JOptionPane.showMessageDialog(this, "Username, password, atau role salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_loginActionPerformed

    private void lblDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMouseClicked
        // TODO add your handling code here:
        this.dispose();

        // Buka form registrasi
        RegistrasiForm reg = new RegistrasiForm();
        reg.setVisible(true);
        reg.pack(); // supaya ukurannya pas
        reg.setLocationRelativeTo(null); // biar muncul di tengah layar
    }//GEN-LAST:event_lblDaftarMouseClicked

    private void pilihanrole_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanrole_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihanrole_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_login;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDaftar;
    private javax.swing.JButton login;
    private javax.swing.JLabel logo_login;
    private javax.swing.JLabel nama_login;
    private javax.swing.JLabel namasistem_login;
    private javax.swing.JComboBox<String> pilihanrole_login;
    private javax.swing.JPasswordField pw_login;
    private javax.swing.JLabel text1_login;
    private javax.swing.JLabel text2_login;
    private javax.swing.JLabel text3_login;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}